<a href="https://colab.research.google.com/github/rayan239/Computer_Vision/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

# Initialize and Casting

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,0,-2,3.0], dtype = tf.float32)
print(tensor_one_d)

tf.Tensor([ 2.  0. -2.  3.], shape=(4,), dtype=float32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2],
    [3,4]
])
print(tensor_two_d)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2],[3,4]],
    [[5,6],[7,8]],
    [[9,10],[11,12]]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]], shape=(3, 2, 2), dtype=int32)


In [ ]:
print(tensor_three_d.shape)

(3, 2, 2)


In [ ]:
print(tensor_three_d.ndim)

3


In [ ]:
tensor_four_d = tf.constant([
    [
    [[1,2],[3,4]],
    [[5,6],[7,8]],
    [[9,10],[11,12]]
    ],

    [
    [[11,12],[23,54]],
    [[55,63],[75,83]],
    [[94,150],[11,12]]
    ],

    [
    [[16,82],[53,84]],
    [[56,67],[78,85]],
    [[957,810],[611,412]]
    ]
])
print(tensor_four_d)

tf.Tensor(
[[[[  1   2]
   [  3   4]]

  [[  5   6]
   [  7   8]]

  [[  9  10]
   [ 11  12]]]


 [[[ 11  12]
   [ 23  54]]

  [[ 55  63]
   [ 75  83]]

  [[ 94 150]
   [ 11  12]]]


 [[[ 16  82]
   [ 53  84]]

  [[ 56  67]
   [ 78  85]]

  [[957 810]
   [611 412]]]], shape=(3, 3, 2, 2), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2.7,0,-2,3.0], dtype = tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d, tf.bool)
casted_tensor_one_d_ = tf.cast(tensor_one_d, tf.int16)
print(tensor_one_d)
print(casted_tensor_one_d)
print(casted_tensor_one_d_)

tf.Tensor([ 2.7  0.  -2.   3. ], shape=(4,), dtype=float32)
tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)
tf.Tensor([ 2  0 -2  3], shape=(4,), dtype=int16)


In [ ]:
tensor_string = tf.constant(['hello','world'])
print(tensor_string)

tf.Tensor([b'hello' b'world'], shape=(2,), dtype=string)


In [ ]:
import numpy as np


In [ ]:
array = np.array([1,2,3,4,5])
tensor_from_array = tf.convert_to_tensor(array)
print(tensor_from_array)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
    num_rows = 5,
    num_columns = None,
    batch_shape = [2,4],
    dtype = tf.dtypes.float32,
    name = None
)
print(3*eye_tensor)

tf.Tensor(
[[[[3. 0. 0. 0. 0.]
   [0. 3. 0. 0. 0.]
   [0. 0. 3. 0. 0.]
   [0. 0. 0. 3. 0.]
   [0. 0. 0. 0. 3.]]

  [[3. 0. 0. 0. 0.]
   [0. 3. 0. 0. 0.]
   [0. 0. 3. 0. 0.]
   [0. 0. 0. 3. 0.]
   [0. 0. 0. 0. 3.]]

  [[3. 0. 0. 0. 0.]
   [0. 3. 0. 0. 0.]
   [0. 0. 3. 0. 0.]
   [0. 0. 0. 3. 0.]
   [0. 0. 0. 0. 3.]]

  [[3. 0. 0. 0. 0.]
   [0. 3. 0. 0. 0.]
   [0. 0. 3. 0. 0.]
   [0. 0. 0. 3. 0.]
   [0. 0. 0. 0. 3.]]]


 [[[3. 0. 0. 0. 0.]
   [0. 3. 0. 0. 0.]
   [0. 0. 3. 0. 0.]
   [0. 0. 0. 3. 0.]
   [0. 0. 0. 0. 3.]]

  [[3. 0. 0. 0. 0.]
   [0. 3. 0. 0. 0.]
   [0. 0. 3. 0. 0.]
   [0. 0. 0. 3. 0.]
   [0. 0. 0. 0. 3.]]

  [[3. 0. 0. 0. 0.]
   [0. 3. 0. 0. 0.]
   [0. 0. 3. 0. 0.]
   [0. 0. 0. 3. 0.]
   [0. 0. 0. 0. 3.]]

  [[3. 0. 0. 0. 0.]
   [0. 3. 0. 0. 0.]
   [0. 0. 3. 0. 0.]
   [0. 0. 0. 3. 0.]
   [0. 0. 0. 0. 3.]]]], shape=(2, 4, 5, 5), dtype=float32)


In [ ]:
fill_tensor = tf.fill(
    [3,4],
    9,
    name = None
)
print(fill_tensor)

tf.Tensor(
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]], shape=(3, 4), dtype=int32)


In [ ]:
 ones_tensor = tf.ones(
    [3,4,2],
    dtype = tf.dtypes.float32,
    name = None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(3, 4, 2), dtype=float32)


In [ ]:
one_like_tensor = tf.ones_like(
    fill_tensor
)
print(one_like_tensor)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)


In [ ]:
zeros_tensor = tf.zeros(
    [3,2],
    dtype = tf.dtypes.float32,
    name = None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [ ]:
print(tf.shape(tensor_three_d))

tf.Tensor([3 2 2], shape=(3,), dtype=int32)


In [ ]:
rank_tensor = tf.rank(tensor_three_d)
print(rank_tensor)

tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
size_tensor = tf.size(tensor_three_d)
print(size_tensor)

tf.Tensor(12, shape=(), dtype=int32)


In [ ]:
random_tensor = tf.random.normal(
    [3,2],
    mean = 100.0,
    stddev = 1.0,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None
)
print(random_tensor)

tf.Tensor(
[[100.750725  98.652115]
 [ 98.38134  100.495514]
 [ 98.23582   99.55065 ]], shape=(3, 2), dtype=float32)


In [ ]:
uniform_tensor = tf.random.uniform(
    [4,3,2],
    minval = 0,
    maxval = 100,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None
)
print(uniform_tensor)
#

tf.Tensor(
[[[27.828323  13.203788 ]
  [59.96665   14.021624 ]
  [35.309196  41.077076 ]]

 [[52.709435   3.1586766]
  [46.448006  93.696304 ]
  [51.64919   57.919014 ]]

 [[82.78192   35.310246 ]
  [96.88254   16.069317 ]
  [77.196625  29.926395 ]]

 [[60.940968   9.289694 ]
  [86.6696    10.347223 ]
  [35.20229    3.2022834]]], shape=(4, 3, 2), dtype=float32)


In [ ]:
 tf.random.set_seed(5)
 print(tf.random.uniform([5,], seed=5))
 print(tf.random.uniform([5,], seed=5))
 print(tf.random.uniform([5,], seed=5))
 print(tf.random.uniform([5,], seed=5))

tf.Tensor([0.15474987 0.85654056 0.84221935 0.4601258  0.13398027], shape=(5,), dtype=float32)
tf.Tensor([0.95445037 0.06285453 0.95480025 0.16461766 0.9124832 ], shape=(5,), dtype=float32)
tf.Tensor([0.41551626 0.17357779 0.22480154 0.93284345 0.1961875 ], shape=(5,), dtype=float32)
tf.Tensor([0.38461006 0.6035322  0.25938308 0.6502763  0.95165634], shape=(5,), dtype=float32)


In [ ]:
 tf.random.set_seed(5)
 print(tf.random.uniform([5,], seed=5))
 print(tf.random.uniform([5,], seed=5))
 print(tf.random.uniform([5,], seed=5))
 print(tf.random.uniform([5,], seed=5))

tf.Tensor([0.15474987 0.85654056 0.84221935 0.4601258  0.13398027], shape=(5,), dtype=float32)
tf.Tensor([0.95445037 0.06285453 0.95480025 0.16461766 0.9124832 ], shape=(5,), dtype=float32)
tf.Tensor([0.41551626 0.17357779 0.22480154 0.93284345 0.1961875 ], shape=(5,), dtype=float32)
tf.Tensor([0.38461006 0.6035322  0.25938308 0.6502763  0.95165634], shape=(5,), dtype=float32)


# Indexing

In [ ]:
tensor_indexed = tf.constant([1,2,3,4,5,6,7,8,9,10])
print(tensor_indexed[0:4])
print(tensor_indexed[1:5:2])

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([2 4], shape=(2,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(tensor_two_d[0:2,1:3])
print(tensor_two_d[...,1])

tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)
tf.Tensor([ 2  6 10], shape=(3,), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2],[3,4]],
    [[5,6],[7,8]],
    [[9,10],[11,12]]
])
print(tensor_three_d[1,0,:])
print(tensor_three_d[:,:,-1])
print(tensor_three_d[ ... , : , -1])

tf.Tensor([5 6], shape=(2,), dtype=int32)
tf.Tensor(
[[ 2  4]
 [ 6  8]
 [10 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  4]
 [ 6  8]
 [10 12]], shape=(3, 2), dtype=int32)


# Math Operations

In [ ]:
x_abs = tf.constant([[1,-2,-3],[-3,-7,-0.3]])
tf.abs(x_abs)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1. , 2. , 3. ],
       [3. , 7. , 0.3]], dtype=float32)>

In [ ]:
tf.abs(-2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
x_abs_complex = tf.constant([-2.034 + 3.997j])
print(tf.abs(x_abs_complex))

print(tf.sqrt((-2.034)**2 + 3.997**2))

tf.Tensor([4.48477034], shape=(1,), dtype=float64)
tf.Tensor(4.4847703, shape=(), dtype=float32)


In [ ]:
x_1 = tf.constant([1,2,3,4,5], dtype=tf.float32)
x_2 = tf.constant([0,7,8,9,10], dtype=tf.float32)
x_3 = tf.constant([5], dtype=tf.float32)
print(tf.add(x_1,x_2))
print(tf.subtract(x_1,x_2))
print(tf.multiply(x_1,x_2))
print(tf.divide(x_1,x_2))
print(tf.math.divide_no_nan(x_1,x_2))
print(tf.math.add(x_1,x_3))#broadcasting

tf.Tensor([ 1.  9. 11. 13. 15.], shape=(5,), dtype=float32)
tf.Tensor([ 1. -5. -5. -5. -5.], shape=(5,), dtype=float32)
tf.Tensor([ 0. 14. 24. 36. 50.], shape=(5,), dtype=float32)
tf.Tensor([       inf 0.2857143  0.375      0.44444445 0.5       ], shape=(5,), dtype=float32)
tf.Tensor([0.         0.2857143  0.375      0.44444445 0.5       ], shape=(5,), dtype=float32)
tf.Tensor([ 6.  7.  8.  9. 10.], shape=(5,), dtype=float32)


In [ ]:
x_3 = tf.constant([[5,3,6,6,4,6]], dtype=tf.float32)
x_4 = tf.constant([[7],[5],[3]], dtype=tf.float32)
print(x_3.shape)
print(x_4.shape)
print(tf.math.multiply(x_3,x_4))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [ ]:
B = tf.constant([[2, 20, 30, 3, 6], [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])
print(tf.math.argmax(B, 0))
print(tf.math.argmax(B, 1))

tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [ ]:
x = tf.constant([2, 4])
y = tf.constant(2)
tf.math.equal(x, y)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [ ]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)  # [[256, 65536], [9, 27]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [ ]:
tensor_two_d = tf.constant([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
], dtype = tf.float16)
print(tf.math.reduce_sum(tensor_two_d))
print(tf.math.reduce_sum(tensor_two_d,0))
print(tf.math.reduce_sum(tensor_two_d,1))
print(tf.math.reduce_max(tensor_two_d,1))
print(tf.math.reduce_mean(tensor_two_d,1))
print(tf.math.reduce_std(tensor_two_d,1, keepdims=True))

tf.Tensor(78.0, shape=(), dtype=float16)
tf.Tensor([15. 18. 21. 24.], shape=(4,), dtype=float16)
tf.Tensor([10. 26. 42.], shape=(3,), dtype=float16)
tf.Tensor([ 4.  8. 12.], shape=(3,), dtype=float16)
tf.Tensor([ 2.5  6.5 10.5], shape=(3,), dtype=float16)
tf.Tensor(
[[1.118]
 [1.118]
 [1.118]], shape=(3, 1), dtype=float16)


In [ ]:
x = tf.constant([0.0, 1.0, 50.0, 100.0])
tf.math.sigmoid(x)# y = 1/(1+e^-x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5      , 0.7310586, 1.       , 1.       ], dtype=float32)>

In [ ]:
result = tf.math.top_k([1, 2, 98, 1, 1, 99, 3, 1, 3, 96, 4, 1],
                        k=3)
print(result)

TopKV2(values=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([99, 98, 96], dtype=int32)>, indices=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 2, 9], dtype=int32)>)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
], dtype = tf.float16)
tf.math.top_k(tensor_two_d,k=2)

TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 4.,  3.],
       [ 8.,  7.],
       [12., 11.]], dtype=float16)>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 2],
       [3, 2],
       [3, 2]], dtype=int32)>)

# Linear Algebra Operations

In [ ]:
 # Matrix Multiplication
 a = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
 b = tf.constant([[12,34],[34,67],[34,67]])
 tf.linalg.matmul(
    a,
    b,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    grad_a=False,
    grad_b=False,
    name=None
)
 # sparse = most of the elements in the matrix are zero
 # adjoint = transpose + conjugate

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 182,  369],
       [ 422,  873],
       [ 662, 1377]], dtype=int32)>

In [ ]:
print(a@b) #Matrix Multiplication

tf.Tensor(
[[ 182  369]
 [ 422  873]
 [ 662 1377]], shape=(3, 2), dtype=int32)


In [ ]:
tf.transpose(a)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int32)>

In [ ]:
a = tf.constant(np.arange(1, 13, dtype=np.int32), shape=[2, 2, 3])
print(a)

b = tf.constant(np.arange(13, 25, dtype=np.int32), shape=[2, 3, 2])
print(b)

c = tf.matmul(a, b)
print(c)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]], shape=(2, 3, 2), dtype=int32)
tf.Tensor(
[[[ 94 100]
  [229 244]]

 [[508 532]
  [697 730]]], shape=(2, 2, 2), dtype=int32)


In [ ]:
# tf.linalg.band_part

input = tf.constant([[ 5,  1,  2, 3],
                [-1,  4,  1, 2],
                [-2, -1,  3, 1],
                [-3, -2, -1, 2]], dtype=tf.float32)

print(tf.linalg.band_part(input, 1, -1))

# (num_lower < 0 || (m-n) <= num_lower)) && (num_upper < 0 || (n-m) <= num_upper)
# if this condition is true then hold the same value otherwise 0.
# m --> rows index
# n --> columns index

print(tf.linalg.band_part(input, 2, 1))

tf.Tensor(
[[ 5.  1.  2.  3.]
 [-1.  4.  1.  2.]
 [ 0. -1.  3.  1.]
 [ 0.  0. -1.  2.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[ 5.  1.  0.  0.]
 [-1.  4.  1.  0.]
 [-2. -1.  3.  1.]
 [ 0. -2. -1.  2.]], shape=(4, 4), dtype=float32)


In [ ]:
 print(tf.linalg.band_part(input, 0, -1)) # Upper triangular part.
 print(tf.linalg.band_part(input, -1, 0)) # Lower triangular part.
 print(tf.linalg.band_part(input, 0, 0)) # Diagonal.

tf.Tensor(
[[5. 1. 2. 3.]
 [0. 4. 1. 2.]
 [0. 0. 3. 1.]
 [0. 0. 0. 2.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[ 5.  0.  0.  0.]
 [-1.  4.  0.  0.]
 [-2. -1.  3.  0.]
 [-3. -2. -1.  2.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[5. 0. 0. 0.]
 [0. 4. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 2.]], shape=(4, 4), dtype=float32)


In [ ]:
inv_two_d = tf.linalg.inv(input) # must be m == n & dtype = float32
print(inv_two_d)

tf.Tensor(
[[ 0.11797752 -0.07865169 -0.07303371 -0.06179776]
 [-0.04494382  0.19662924 -0.06741572 -0.09550563]
 [ 0.01685394 -0.01123596  0.2752809  -0.15168539]
 [ 0.14044943  0.07303371 -0.03932585  0.23595506]], shape=(4, 4), dtype=float32)


In [ ]:
print(input@inv_two_d) #identity matrix

tf.Tensor(
[[ 1.0000000e+00  2.9802322e-08  0.0000000e+00  0.0000000e+00]
 [ 1.4901161e-08  1.0000001e+00  0.0000000e+00 -1.4901161e-08]
 [ 0.0000000e+00 -2.2351742e-08  1.0000000e+00  2.9802322e-08]
 [ 0.0000000e+00 -4.4703484e-08 -2.9802322e-08  1.0000000e+00]], shape=(4, 4), dtype=float32)


In [ ]:
 print(input)
 s,u,v = tf.linalg.svd(input)
 print(s)
 print(u)
 print(v)

tf.Tensor(
[[ 5.  1.  2.  3.]
 [-1.  4.  1.  2.]
 [-2. -1.  3.  1.]
 [-3. -2. -1.  2.]], shape=(4, 4), dtype=float32)
tf.Tensor([6.9071856 4.849908  3.932922  2.7020917], shape=(4,), dtype=float32)
tf.Tensor(
[[ 0.86190313  0.02946658  0.4517349   0.22845227]
 [ 0.25355366  0.75394666 -0.5939214   0.12055088]
 [-0.11985409  0.55115664  0.5179587  -0.643102  ]
 [-0.42245558  0.35626206  0.41822463  0.7209002 ]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[ 0.8053983  -0.57273525  0.14289764  0.05374139]
 [ 0.41129375  0.36734125 -0.8335683  -0.03258308]
 [ 0.29538122  0.43507788  0.36746216 -0.76709104]
 [ 0.30809242  0.5896964   0.38693127  0.63845235]], shape=(4, 4), dtype=float32)


In [ ]:
### np.einsum
Q = np.random.randn(32, 64, 512)
K = np.random.randn(32, 128, 512)

np.einsum('bqm,bkm -> bqk', Q, K).shape # QK^T

(32, 64, 128)

In [ ]:
q = np.random.randn(2, 4, 4, 2) # bcij
k = np.random.randn(2, 4, 4, 1) # bcik

np.einsum('bcik,bcij -> bckj', k, q) # k^Tq

array([[[[ 0.35224046,  3.32645162]],

        [[-3.28268439,  5.67326784]],

        [[ 3.1164247 ,  2.96778731]],

        [[-1.13766647,  0.60610753]]],


       [[[ 1.94558868, -0.11023614]],

        [[ 5.92403246,  3.0469428 ]],

        [[ 3.31873678,  1.16222682]],

        [[-1.68281956,  2.69776126]]]])

In [ ]:
np.matmul(np.transpose(k,(0,1,3,2)),q)

array([[[[ 0.35224046,  3.32645162]],

        [[-3.28268439,  5.67326784]],

        [[ 3.1164247 ,  2.96778731]],

        [[-1.13766647,  0.60610753]]],


       [[[ 1.94558868, -0.11023614]],

        [[ 5.92403246,  3.0469428 ]],

        [[ 3.31873678,  1.16222682]],

        [[-1.68281956,  2.69776126]]]])

### FUNCTIONS

In [ ]:
# tf.expand_dims
three_dimensional_tensor =tf.constant(
     [
	[
		[1, 2, 3],
		[4, 5, 6]
	],
	[
		[7, 8, 9],
		[10, 11, 12]
	]
]

)

print(three_dimensional_tensor.shape)
print(tf.expand_dims(three_dimensional_tensor, axis=0).shape)
print(tf.expand_dims(three_dimensional_tensor, axis=1).shape)
print(tf.expand_dims(three_dimensional_tensor, axis=2).shape)

(2, 2, 3)
(1, 2, 2, 3)
(2, 1, 2, 3)
(2, 2, 1, 3)


In [ ]:
# tf.squeeze

# Expand a dimension to size 1 at axis 0 for demonstration
expanded_tensor = tf.expand_dims(three_dimensional_tensor, axis=0)
print("Original shape:", three_dimensional_tensor.shape)
print("Expanded shape:", expanded_tensor.shape)

# Now squeeze the dimension of size 1 (axis 0)
x_squeezed = tf.squeeze(expanded_tensor, axis=0)

print("Squeezed tensor:")
print(x_squeezed)
print("Squeezed shape:", x_squeezed.shape)

Original shape: (2, 2, 3)
Expanded shape: (1, 2, 2, 3)
Squeezed tensor:
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
Squeezed shape: (2, 2, 3)


In [ ]:
# tf.reshape

x_reshape = tf.constant([[1,2,3,4],
                         [5,6,7,8]])
print(x_reshape.shape)
print(tf.reshape(x_reshape, [8]))
print(tf.reshape(x_reshape, [4,2]))
print(tf.reshape(x_reshape, [2,2,2]))
print(tf.reshape(x_reshape, [4,-1]))
print(tf.reshape(x_reshape, [4,1,-1]))# for -1, program automatically detect the desired shape


(2, 4)
tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[[1 2]]

 [[3 4]]

 [[5 6]]

 [[7 8]]], shape=(4, 1, 2), dtype=int32)


In [ ]:
# tf.concat
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]
print(tf.concat([t1, t2], 0))
print(tf.concat([t1, t2], 1))

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


In [ ]:
t1 = [[[1, 2, 3], [4, 5, 6]]]
t2 = [[[7, 8, 9], [10, 11, 12]]]
print(tf.constant(t1).shape)
print(tf.constant(t2).shape)
print(tf.concat([t1, t2], 0))
print(tf.concat([t1, t2], 1))

(1, 2, 3)
(1, 2, 3)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]], shape=(1, 4, 3), dtype=int32)


In [ ]:
# tf.stack
t3 = tf.stack([t1, t2, t1], 0)
print(t3)

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]]


 [[[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]]]], shape=(3, 1, 2, 3), dtype=int32)


In [ ]:
# tf.pad

t = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[1, 2,], [3, 4]]) # top, bottom, left, right
print(tf.pad(t, paddings, "CONSTANT"))

tf.Tensor(
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 2 3 0 0 0 0]
 [0 0 0 4 5 6 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]], shape=(5, 10), dtype=int32)


In [ ]:
# tf.gather

params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
print(params[1:4])
print(tf.gather(params,tf.range(1,4)))

tf.Tensor([b'p1' b'p2' b'p3'], shape=(3,), dtype=string)
tf.Tensor([b'p1' b'p2' b'p3'], shape=(3,), dtype=string)


In [ ]:

input = tf.constant([[ 5,  1,  2, 3],
                [-1,  4,  1, 2],
                [-2, -1,  3, 1],
                [-3, -2, -1, 2]], dtype=tf.float32)

print(input.shape)
print(tf.gather(input, [0,2], axis = 0))
print(tf.gather(input, [0,2], axis = 1))

(4, 4)
tf.Tensor(
[[ 5.  1.  2.  3.]
 [-2. -1.  3.  1.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 5.  2.]
 [-1.  1.]
 [-2.  3.]
 [-3. -1.]], shape=(4, 2), dtype=float32)


In [ ]:
input = tf.constant([

                [[ 5,  1,  2, 3],
                [-1,  4,  1, 2],
                [-2, -1,  3, 1],
                [-3, -2, -1, 2]]

                ])

print(input.shape)
print(tf.gather(input, [0], axis = 0))
print(tf.gather(input, [0,2], axis = 1))
print(tf.gather(input, [0,2], axis = 2))

(1, 4, 4)
tf.Tensor(
[[[ 5  1  2  3]
  [-1  4  1  2]
  [-2 -1  3  1]
  [-3 -2 -1  2]]], shape=(1, 4, 4), dtype=int32)
tf.Tensor(
[[[ 5  1  2  3]
  [-2 -1  3  1]]], shape=(1, 2, 4), dtype=int32)
tf.Tensor(
[[[ 5  2]
  [-1  1]
  [-2  3]
  [-3 -1]]], shape=(1, 4, 2), dtype=int32)


In [ ]:
# tf.gather_nd

indices=[[0,1]]
params = [['a', 'b'],
           ['c', 'd']]
print(tf.gather_nd(params, indices))
print(tf.gather(params, indices))

tf.Tensor([b'b'], shape=(1,), dtype=string)
tf.Tensor(
[[[b'a' b'b']
  [b'c' b'd']]], shape=(1, 2, 2), dtype=string)


In [ ]:
indices=[[0,1],[1,0]]
params = [[['a', 'b'],
           ['c', 'd']],
          [['a0', 'b0'],
           ['c0', 'd0']]]
print(tf.gather_nd(params, indices))
print(tf.gather(params, indices))

print(tf.gather_nd(params, indices, batch_dims = 1))

tf.Tensor(
[[b'c' b'd']
 [b'a0' b'b0']], shape=(2, 2), dtype=string)
tf.Tensor(
[[[[b'a' b'b']
   [b'c' b'd']]

  [[b'a0' b'b0']
   [b'c0' b'd0']]]


 [[[b'a0' b'b0']
   [b'c0' b'd0']]

  [[b'a' b'b']
   [b'c' b'd']]]], shape=(2, 2, 2, 2), dtype=string)
tf.Tensor([b'b' b'c0'], shape=(2,), dtype=string)


# Ragged Tensors

In [ ]:
tensor_two_d = tf.ragged.constant([
    [1,2,3,4],
    [5,6],
    [9]
])
# Non-rectangular Tensor
print(tensor_two_d.shape)

(3, None)


In [ ]:
print(tf.RaggedTensor.from_row_lengths(
      values=[3, 1, 4, 1, 5, 9, 2, 6],
      row_lengths=[4,0,3,1,0]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [ ]:
print(tf.RaggedTensor.from_row_limits(
      values=[3, 1, 4, 1, 5, 9, 2, 6],
      row_limits=[0, 4, 4, 7, 8, 8]))

<tf.RaggedTensor [[], [3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [ ]:
print(tf.RaggedTensor.from_row_splits(
      values=[3, 1, 4, 1, 5, 9, 2, 6],
      row_splits=[0, 4, 4, 7, 8, 8]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


# SPARSE TENSORS

In [ ]:
sparse_tensor = tf.sparse.SparseTensor(
    indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4]
)

In [ ]:
tf.sparse.to_dense(sparse_tensor)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 0]], dtype=int32)>

# String Tensors

In [ ]:
tf.strings.join([['abc','123'],
                 ['def','456'],
                 ['ghi','789']], separator="+")

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'abc+def+ghi', b'123+456+789'], dtype=object)>

# Variables

In [ ]:
x = tf.constant([1,2])
x_var = tf.Variable(x, name = 'var1')
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [ ]:
x_var.assign_sub([3,4])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([-2, -2], dtype=int32)>

In [ ]:
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([-2, -2], dtype=int32)>


In [ ]:
x_var.assign_add([2,3])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([0, 1], dtype=int32)>

In [ ]:
with tf.device('CPU:0'):
  x_var = tf.Variable(0.2)
  x_tensor = tf.constant(0.2)
print(x_var.device)
print(x_tensor.device)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0


# See you not for mind